'use client';

import { useEffect,useState } from 'react';
import { authorizedFetch,getBrowserSupabase } from '@/lib/supabase/browser';

type CompetitorInput={name:string;domain:string};
export default function CompetitorsPage(){
 const [siteId,setSiteId]=useState('');const [rows,setRows]=useState<Record<string,any>[]>([]);const [inputs,setInputs]=useState<CompetitorInput[]>([{name:'',domain:''}]);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');
 async function load(){const supabase=await getBrowserSupabase();const session=await supabase.auth.getSession();if(!session.data.session?.user)return void(window.location.href='/login');const member=await supabase.from('organization_memberships').select('organization_id').eq('user_id',session.data.session.user.id).limit(1).maybeSingle();if(!member.data)return void(window.location.href='/dashboard');const site=await supabase.from('sites').select('id').eq('organization_id',member.data.organization_id).limit(1).maybeSingle();if(!site.data)return;setSiteId(site.data.id);const competitors=await supabase.from('competitors').select('*').eq('site_id',site.data.id).order('updated_at',{ascending:false});setRows(competitors.data??[])}
 useEffect(()=>{load().catch((error)=>setMessage(error instanceof Error?error.message:'Competitors could not load.'))},[]);
 async function research(event:React.FormEvent){event.preventDefault();setBusy(true);setMessage('');try{const competitors=inputs.filter((item)=>item.name.trim()&&item.domain.trim());const response=await authorizedFetch('/api/research/competitors',{method:'POST',body:JSON.stringify({siteId,competitors})});const payload=await response.json();if(!response.ok)throw new Error(payload.error??'Competitor research failed.');setMessage(`Compared ${payload.snapshots.length} competitor websites.`);await load()}catch(error){setMessage(error instanceof Error?error.message:'Competitor research failed.')}finally{setBusy(false)}}
 return <main className="google-setup-page"><section className="google-setup-card"><a className="app-brand" href="/dashboard"><span className="app-brand-mark">L</span><span>Luna <small>Competitor research</small></span></a><div><span className="kicker">Public evidence comparison</span><h1>Compare what customers actually see.</h1><p>Luna reviews competitor service pages, content depth, CTAs, trust signals, internal linking and visible offers. It does not invent traffic, revenue or conversion data.</p></div>{message&&<div className="notice">{message}</div>}<form className="stack-form" onSubmit={research}>{inputs.map((item,index)=><div className="inline-form" key={index}><input required placeholder="Competitor name" value={item.name} onChange={(event)=>setInputs(inputs.map((row,i)=>i===index?{...row,name:event.target.value}:row))}/><input required placeholder="https://competitor.com" value={item.domain} onChange={(event)=>setInputs(inputs.map((row,i)=>i===index?{...row,domain:event.target.value}:row))}/>{inputs.length>1&&<button type="button" className="danger-button" onClick={()=>setInputs(inputs.filter((_row,i)=>i!==index))}>Remove</button>}</div>)}<div className="button-row"><button type="button" className="secondary-button" disabled={inputs.length>=5} onClick={()=>setInputs([...inputs,{name:'',domain:''}])}>Add competitor</button><button className="app-button" disabled={!siteId||busy}>{busy?'Researching…':'Run competitor snapshot'}</button><a className="secondary-button" href="/dashboard">Return to Luna</a></div></form><div className="card-list">{rows.map((item)=><article className="panel" key={item.id}><span className="kicker">{item.source}</span><h3>{item.name}</h3><p>{item.domain}</p><div className="dashboard-grid"><div><strong>Strengths</strong><ul>{(item.strengths??[]).map((value:string)=><li key={value}>{value}</li>)}</ul></div><div><strong>Weaknesses</strong><ul>{(item.weaknesses??[]).map((value:string)=><li key={value}>{value}</li>)}</ul></div></div><details><summary>View evidence snapshot</summary><pre className="draft-copy">{JSON.stringify(item.snapshot,null,2)}</pre></details></article>)}</div></section></main>
}
