'use client';

import { useEffect, useState } from 'react';
import { authorizedFetch, getBrowserSupabase } from '@/lib/supabase/browser';

export default function LocalAuditPage(){
 const [siteId,setSiteId]=useState(''); const [runs,setRuns]=useState<Record<string,any>[]>([]); const [findings,setFindings]=useState<Record<string,any>[]>([]); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 async function load(){const supabase=await getBrowserSupabase();const session=await supabase.auth.getSession();if(!session.data.session?.user)return void(window.location.href='/login');const member=await supabase.from('organization_memberships').select('organization_id').eq('user_id',session.data.session.user.id).limit(1).maybeSingle();if(!member.data)return void(window.location.href='/dashboard');const site=await supabase.from('sites').select('id').eq('organization_id',member.data.organization_id).limit(1).maybeSingle();if(!site.data)return;setSiteId(site.data.id);const [r,f]=await Promise.all([supabase.from('audit_runs').select('*').eq('site_id',site.data.id).eq('audit_type','local').order('created_at',{ascending:false}).limit(10),supabase.from('audit_findings').select('*').eq('site_id',site.data.id).eq('category','local SEO').order('created_at',{ascending:false}).limit(200)]);setRuns(r.data??[]);setFindings(f.data??[])}
 useEffect(()=>{load().catch((error)=>setMessage(error instanceof Error?error.message:'Local audit could not load.'))},[]);
 async function run(){setBusy(true);setMessage('');try{const response=await authorizedFetch('/api/audits/local',{method:'POST',body:JSON.stringify({siteId})});const payload=await response.json();if(!response.ok)throw new Error(payload.error??'Local audit failed.');setMessage(`Local SEO audit completed with a score of ${payload.summary.score}/100.`);await load()}catch(error){setMessage(error instanceof Error?error.message:'Local audit failed.')}finally{setBusy(false)}}
 const latest=runs[0];
 return <main className="google-setup-page"><section className="google-setup-card"><a className="app-brand" href="/dashboard"><span className="app-brand-mark">L</span><span>Luna <small>Local SEO audit</small></span></a><div><span className="kicker">Map, profile and location relevance</span><h1>Audit the complete local visibility foundation.</h1><p>Luna evaluates GBP completeness, categories, website and phone consistency, reviews, citations, local keywords, target-location coverage and competitors.</p></div>{message&&<div className="notice">{message}</div>}<div className="button-row"><button className="app-button" disabled={!siteId||busy} onClick={run}>{busy?'Running audit…':'Run local SEO audit'}</button><a className="secondary-button" href="/dashboard">Return to Luna</a></div><section className="metric-row"><article className="metric"><span>Local score</span><strong>{latest?.summary?.score??'—'}</strong><small>Evidence weighted</small></article><article className="metric"><span>GBP</span><strong>{latest?.summary?.gbpConnected?'Connected':'Missing'}</strong><small>{latest?.summary?.gbpLocations??0} locations</small></article><article className="metric"><span>Reviews</span><strong>{latest?.summary?.reviews??0}</strong><small>{latest?.summary?.averageRating?`${Number(latest.summary.averageRating).toFixed(1)} average`:'No rating'}</small></article><article className="metric"><span>Citation issues</span><strong>{latest?.summary?.citationIssues??0}</strong><small>{latest?.summary?.citations??0} tracked</small></article></section><section className="panel"><div className="table-wrap"><table><thead><tr><th>Severity</th><th>Finding</th><th>Evidence</th></tr></thead><tbody>{findings.map((item)=><tr key={item.id}><td><span className={`severity ${item.severity}`}>{item.severity}</span></td><td><strong>{item.title}</strong><small>{item.description}</small></td><td><code>{JSON.stringify(item.evidence)}</code></td></tr>)}</tbody></table></div></section></section></main>
}
